version: '3.0'
services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: unless-stopped
    networks:
      - misago
    ports:
      - "8080:80"
    volumes:
      - misago-media:/misago/media
      - misago-static:/misago/static
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./config/vhost.d:/etc/nginx/vhost.d:ro
      - ./logs/nginx:/var/log/nginx:z

  postgres:
    image: postgres:10
    restart: unless-stopped
    networks:
      - misago
    env_file:
      - ./config/postgres.env
    volumes:
      - misago-database:/var/lib/postgresql/data

  redis:
    image: redis:4
    restart: unless-stopped
    networks:
      - misago
    volumes:
      - misago-redis:/data

  misago:
    build: misago
    restart: unless-stopped
    networks:
      misago:
        aliases:
          - misago
    environment:
      - POSTGRES_HOST=postgres
      - VIRTUAL_PROTO=uwsgi
    env_file:
      - ./config/misago.env
      - ./config/postgres.env
    depends_on:
      - postgres
      - redis
    volumes:
      - misago-media:/misago/media
      - misago-static:/misago/static
      - ./misago/avatargallery:/misago/avatargallery:ro
      - ./misago/theme:/misago/theme:ro
      - ./backups:/misago/backups:Z
      - ./logs:/misago/logs:z

networks:
  misago:

volumes:
  misago-database:
  misago-media:
  misago-redis:
  misago-static: