version: '3.0'
services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    networks:
      - misago
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ENABLE_IPV6=true
    depends_on:
      - misago
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - misago-media:/misago/media
      - misago-static:/misago/static
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./config/certs:/etc/nginx/certs:ro
      - ./config/vhost.d:/etc/nginx/vhost.d:z
      - ./logs/nginx:/var/log/nginx:z

  nginx-lets-encrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    networks:
      - misago
    depends_on:
      - nginx-proxy
    volumes:
      - /usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/certs:/etc/nginx/certs:rw
      - ./config/vhost.d:/etc/nginx/vhost.d:z

  postgres:
    image: postgres:10
    restart: unless-stopped
    networks:
      - misago
    env_file:
      - ./config/postgres.env
    volumes:
      - misago-database:/var/lib/postgresql/data

  redis:
    image: redis:5
    restart: unless-stopped
    networks:
      - misago
    volumes:
      - misago-redis:/data

  misago:
    build: misago
    restart: unless-stopped
    networks:
      misago:
        aliases:
          - misago
    environment:
      - POSTGRES_HOST=postgres
      - VIRTUAL_PROTO=uwsgi
    env_file:
      - ./config/misago.env
      - ./config/postgres.env
    depends_on:
      - postgres
      - redis
    volumes:
      - misago-media:/misago/media
      - misago-static:/misago/static
      - ./misago/avatargallery:/misago/avatargallery:ro
      - ./misago/theme:/misago/theme:ro
      - ./backups:/misago/backups:Z
      - ./logs:/misago/logs:z

networks:
  misago:

volumes:
  misago-database:
  misago-media:
  misago-redis:
  misago-static: